name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.6
      with:
        cli: 1.12.0.1479

    - name: Cache clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        # List all files containing dependencies:
        key: cljdeps-${{ hashFiles('deps.edn') }}

    - name: Linter
      run: clojure -M:clj-kondo --lint src

    - name: Install karma
      run: npm install -g karma karma-cljs-test karma-chrome-launcher karma-firefox-launcher

    - name: Run JVM tests
      run: clojure -X:test

    - name: Run ClojureScript tests (Chrome)
      run:  clojure -M:cljs-test -x chrome-headless

    - name: Run ClojureScript tests (Firefox)
      run:  clojure -M:cljs-test -x firefox-headless
